name: Build
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  controller:
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.calculate-jobs.outputs.jobs }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh workflow run msvc.yml
