name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_REGION: eu
